# Site settings
title: 'codeSin(s||z)' # Your Title
tagline: 'Of JavaScript, life, and everything inbetween.' # A brief tagline for your site
keywords : 'programming, blog, tutorials, technical, javascript'
description : 'Code Sinz is an opinionated blog about JavaScript, life and everything inbetween. It is maintained by Adrian Oprea, a software developer heavily focused on JavaScript. Adrian also likes to read, travel and enjoy life.'
sidebar_image: /images/cover.png
domain_name: 'codesi.nz'

creator :
    name : 'Adrian Oprea'
    twitter : '@opreaadrian'

# Build settings
markdown: redcarpet
highlighter_theme: tomorrow
baseurl:  # the subpath of your site, e.g. /blog/

google :
    analytics : 'UA-32468134-4'
    googleplus: '+AdrianOpreasWeb'
