source 'https://rubygems.org'

gem 'jekyll'
gem 'github-pages'
gem 'jekyll-sass'
gem 'jekyll-sass-converter'
gem 'jekyll-sitemap'
gem 'jekyll-prism-plugin'
gem 'jekyll-feed'
gem 'kramdown'
gem 'rouge'
gem 'jekyll-watch'
