# Site wide configuration

title: CODE SIN{Z}
description: "Opinionated blog about JavaScript, life, and everything inbetween."
logo: # 120x120 px default image used for Twitter summary card
teaser: false # 400x250 px default teaser image used in image archive grid
locale: en-US
url: http://blog.codesi.nz
# url: http://localhost:4000/
# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Adrian Oprea
  email:
  twitter: opreaadrian
  google:
    ad-client:
    ad-slot:
    analytics: UA-32468134-4
    plus: AdrianOpreasWeb
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: webrambler


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
